### PR TITLE
Fix VocaDbUserManager.GetLoggedInUserName

### LINKED ISSUE #2: Unable to log in to the wiki
**Website**
VocaDB wiki

https://wiki.vocadb.net/User/Login

Message "Sorry, an error occurred while processing your request. " appears when trying to log in to the VocaDB wiki (username + access key).

### PR DESCRIPTION
**Pull request by ycanardeau**
Fixes #2.

### CODE REVIEW

File: RoadkillVocaDbAuth/VocaDbUserManager.cs [hunk 1]
```diff
@@ -143,16 +147,20 @@ public override bool DeleteUser(string email)
...
 		{
-			if (FormsAuthentication.IsEnabled)
+			var cookie = context.Request.Cookies[".AspNetCore.Cookies"];
+			if (cookie != null)
 			{
-				if (context.Request.Cookies[FormsAuthentication.FormsCookieName] != null)
+				var cookieContainer = new CookieContainer();
+				cookieContainer.Add(new Cookie(name: cookie.Name, value: cookie.Value, path: cookie.Path, domain: ".vocadb.net"/* TODO: do not hardcode */));
+				using (var handler = new HttpClientHandler { CookieContainer = cookieContainer })
+				using (var client = new HttpClient(handler))
```
Comment (riipah) [inline RoadkillVocaDbAuth/VocaDbUserManager.cs:158]: Actually the HttpClient should not be created every time, but I'm not sure if it's really an issue, https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

I'm sure there's a way to pass the cookie in some other way?

File: RoadkillVocaDbAuth/VocaDbUserManager.cs [hunk 2]
```diff
@@ -143,16 +147,20 @@ public override bool DeleteUser(string email)
 
 		public override string GetLoggedInUserName(HttpContextBase context)
 		{
-			if (FormsAuthentication.IsEnabled)
+			var cookie = context.Request.Cookies[".AspNetCore.Cookies"];
```
Comment (riipah) [inline RoadkillVocaDbAuth/VocaDbUserManager.cs]: Cookie name could be named constant too

File: RoadkillVocaDbAuth/VocaDbUserManager.cs [hunk 3]
```diff
@@ -33,6 +34,9 @@ public class UserForApiContract
 	{
 		[DataMember]
 		public UserGroupId GroupId { get; set; }
+
+		[DataMember]
+		public string Name { get; set; }
```
Comment (riipah) [inline RoadkillVocaDbAuth/VocaDbUserManager.cs:39]: Were we really using User.Name? I thought it was Email... But I could be wrong. No, it's probably correct like this.

**Comment by riipah** [comment]
Might check if you can do something about the HttpClient since it can apparently cause resource starvation, but if not, I think it's fine like that too. Thanks!

File: RoadkillVocaDbAuth/VocaDbUserManager.cs (hunk 1 above)
Comment (ycanardeau) [reply RoadkillVocaDbAuth/VocaDbUserManager.cs:158]: I tried `SendAsync` along with `HttpRequestMessage.Headers.Add` instead of `GetStringAsync (this worked fine in a console application), but it causes a runtime error for some reason. I'll keep this as is for now.

**Comment by ycanardeau** [comment]
Thanks for reviewing this!
